# -*- coding: utf-8 -*-
"""Distribusi Usia Penumpang Titanic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15kkyMzlKOZbYqd1TjnWyNow3x008KDRN
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries berhasil diimpor!")

# URL dari dataset Titanic yang sudah bersih
url = 'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

# Baca data dari URL dan simpan ke dalam sebuah variabel bernama 'df' (singkatan dari DataFrame)
df = pd.read_csv(url)

# Tampilkan 5 baris pertama dari data untuk memastikan data sudah termuat
df.head()

# Atur gaya grafik agar lebih menarik
sns.set_style("whitegrid")

# Buat grafik hitung (countplot) untuk kolom 'Survived'
plt.figure(figsize=(8, 5)) # Mengatur ukuran gambar
sns.countplot(x='Survived', data=df)
plt.title('Jumlah Penumpang Selamat vs Tidak Selamat')
plt.xticks([0, 1], ['Tidak Selamat', 'Selamat']) # Mengganti label 0 dan 1
plt.xlabel('Status Keselamatan')
plt.ylabel('Jumlah Penumpang')
plt.show() # Menampilkan grafik

# Buat countplot untuk status keselamatan dengan pembeda warna (hue) berdasarkan jenis kelamin
plt.figure(figsize=(8, 5))
sns.countplot(x='Survived', hue='Sex', data=df)
plt.title('Keselamatan Berdasarkan Jenis Kelamin')
plt.xticks([0, 1], ['Tidak Selamat', 'Selamat'])
plt.xlabel('Status Keselamatan')
plt.ylabel('Jumlah Penumpang')
plt.legend(title='Jenis Kelamin')
plt.show()

# Buat countplot untuk status keselamatan dengan pembeda warna (hue) berdasarkan kelas tiket
plt.figure(figsize=(10, 6))
sns.countplot(x='Survived', hue='Pclass', data=df)
plt.title('Keselamatan Berdasarkan Kelas Tiket')
plt.xticks([0, 1], ['Tidak Selamat', 'Selamat'])
plt.xlabel('Status Keselamatan')
plt.ylabel('Jumlah Penumpang')
plt.legend(title='Kelas Tiket')
plt.show()

# Buat histogram untuk kolom 'Age'
plt.figure(figsize=(10, 6))
sns.histplot(df['Age'].dropna(), bins=30, kde=True) # dropna() untuk mengabaikan data usia yang kosong
plt.title('Distribusi Usia Penumpang')
plt.xlabel('Usia')
plt.ylabel('Frekuensi')
plt.show()

